// Product interface for type safety
export interface Product {
  id: number;
  name: string;
  price: number;
  description: string;
  category: string;
  brand: string;
  image: string;
  rating: number;
  reviews: number;
  sku: string;
  oem: string;
  oemPN: string;
  katunPN: string;
  comments: string;
  forUseIn: string;
}

// Product data from Katun Price List
export const products: Product[] = [
  {
    id: 1,
    name: "Transfer Belt",
    price: 188.15,
    description: "Packaged for use in Konica and Okidata",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "56255",
    oem: "Konica Minolta",
    oemPN: "A1DU504203",
    katunPN: "56255",
    comments: "Priced Each, Sold Each.  15 Boxes per Master Carton",
    forUseIn: "BIZHUB PRESS C 1060, BIZHUB PRESS C 1070, BIZHUB PRESS C 1070 P, BIZHUB PRESS C 6000, BIZHUB PRESS C 6000 PRO, BIZHUB PRESS C 7000, BIZHUB PRESS C 7000 P, BIZHUB PRESS C 71 CF, BIZHUB PRESS C 71 HC"
  },
  {
    id: 2,
    name: "Image Transfer Belt",
    price: 174.9,
    description: "Belt Only, Packaged for use in Konica Minolta",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "48440",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "48440",
    comments: "Priced Each, sold in Boxes of 1.  15 Boxes per Master Carton",
    forUseIn: "BIZHUB C 221, BIZHUB C 221 S, BIZHUB C 224, BIZHUB C 224 E, BIZHUB C 258, BIZHUB C 281, BIZHUB C 284, BIZHUB C 284 E, BIZHUB C 308, BIZHUB C 364, BIZHUB C 364 E, BIZHUB C 368, BIZHUB C 454, BIZHUB C 454 E, BIZHUB C 458, BIZHUB C 458 E, BIZHUB C 554, BIZHUB C 554 E, BIZHUB C 7122, BIZHUB C 7128"
  },
  {
    id: 3,
    name: "Drum Cleaning Blade",
    price: 10.07,
    description: "For DR-313/DR-512 Drum Units",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "43973",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "43973",
    comments: "Priced Each, sold in Boxes of 1.  50 Boxes per Master Carton",
    forUseIn: "BIZHUB 224 E, BIZHUB 284 E, BIZHUB 364 E, BIZHUB 454 E, BIZHUB 554 E, BIZHUB C 224, BIZHUB C 224 E, BIZHUB C 284, BIZHUB C 284 E, BIZHUB C 364, BIZHUB C 364 E, BIZHUB C 454, BIZHUB C 454 E, BIZHUB C 554, BIZHUB C 554 E"
  },
  {
    id: 4,
    name: "Transfer Belt Cleaning Blade",
    price: 12.72,
    description: "Packaged for use in Konica Minolta",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49171",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49171",
    comments: "Priced Each, sold in Boxes of 1.  50 Boxes per Master Carton",
    forUseIn: "BIZHUB C 220, BIZHUB C 224, BIZHUB C 224 E, BIZHUB C 258, BIZHUB C 280, BIZHUB C 284, BIZHUB C 284 E, BIZHUB C 308, BIZHUB C 360, BIZHUB C 364, BIZHUB C 364 E, BIZHUB C 368, BIZHUB C 458, BIZHUB C 458 E"
  },
  {
    id: 5,
    name: "Chip, Black",
    price: 37.9,
    description: "Drum Unit Cartridge",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "37649",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "37649",
    comments: "Priced per Bag, sold 1 per Bag.",
    forUseIn: "BIZHUB C 220, BIZHUB C 280, BIZHUB C 360"
  },
  {
    id: 6,
    name: "Chip, Cyan/Yellow/Magenta",
    price: 39.5,
    description: "For Color / DR512 and DR313",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "47285",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "47285",
    comments: "Priced per Bag, sold 1 per Bag.",
    forUseIn: "BIZHUB C 221, BIZHUB C 221 S, BIZHUB C 224, BIZHUB C 224 E, BIZHUB C 250 I, BIZHUB C 251 I, BIZHUB C 258, BIZHUB C 281, BIZHUB C 284, BIZHUB C 284 E, BIZHUB C 300 I, BIZHUB C 301 I, BIZHUB C 308, BIZHUB C 360 I, BIZHUB C 361 I, BIZHUB C 364, BIZHUB C 364 E, BIZHUB C 368, BIZHUB C 454, BIZHUB C 454 E, BIZHUB C 458, BIZHUB C 458 E, BIZHUB C 554, BIZHUB C 554 E, BIZHUB C 558, BIZHUB C 658"
  },
  {
    id: 7,
    name: "Chip, Cyan/Yellow/Magenta/Black",
    price: 15.5,
    description: "Imaging Unit Cartridge",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "52758",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "52758",
    comments: "Priced per Bag, sold 1 per Bag.",
    forUseIn: "BIZHUB C 3300 I, BIZHUB C 3320 I, BIZHUB C 3350 I, BIZHUB C 3351, BIZHUB C 3851, BIZHUB C 4000 I, BIZHUB C 4050 I"
  },
  {
    id: 8,
    name: "Chip, Cyan/Yellow/Magenta",
    price: 17.49,
    description: "Drum Unit Cartridge",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "52760",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "52760",
    comments: "Priced per Bag, sold 1 per Bag.",
    forUseIn: "BIZHUB C 450 I, BIZHUB C 550 I, BIZHUB C 650 I"
  },
  {
    id: 9,
    name: "Drum Charge Roller",
    price: 36.04,
    description: "Packaged for use in Konica Minolta",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "43972",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "43972",
    comments: "Priced Each, sold in Boxes of 1.  20 Boxes per Master Carton",
    forUseIn: "BIZHUB 223, BIZHUB 224, BIZHUB 224 E, BIZHUB 282, BIZHUB 283, BIZHUB 284, BIZHUB 284 E, BIZHUB 362, BIZHUB 363, BIZHUB 364, BIZHUB 364 E, BIZHUB 423, BIZHUB 552, BIZHUB 554, BIZHUB 554 E, BIZHUB 652, BIZHUB 654, BIZHUB 654 E, BIZHUB 752, BIZHUB 754, BIZHUB 754 E"
  },
  {
    id: 10,
    name: "Yellow Developer Unit",
    price: 429.3,
    description: "Equivalent to DV-512Y, Yellow, Universal",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49170",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49170",
    comments: "Priced Each, Sold Each.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 224, BIZHUB C 284, BIZHUB C 364, BIZHUB C 454, BIZHUB C 554"
  },
  {
    id: 11,
    name: "Magenta Developer Unit",
    price: 429.3,
    description: "Equivalent to DV-512M, Magenta, Universal",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49169",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49169",
    comments: "Priced Each, Sold Each.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 224, BIZHUB C 284, BIZHUB C 364, BIZHUB C 454, BIZHUB C 554"
  },
  {
    id: 12,
    name: "Cyan Developer Unit",
    price: 429.3,
    description: "Equivalent to DV-512C, Cyan, Universal",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49168",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49168",
    comments: "Priced Each, Sold Each.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 224, BIZHUB C 284, BIZHUB C 364, BIZHUB C 454, BIZHUB C 554"
  },
  {
    id: 13,
    name: "Black Developer Unit",
    price: 429.3,
    description: "Equivalent to DV-512K, Black, Universal",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49167",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49167",
    comments: "Priced Each, Sold Each.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 224, BIZHUB C 284, BIZHUB C 364, BIZHUB C 454, BIZHUB C 554"
  },
  {
    id: 14,
    name: "Separation Roller",
    price: 16.79,
    description: "Packaged for use in Konica Minolta",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49075",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49075",
    comments: "Priced Each, sold in Boxes of 1.  20 Boxes per Master Carton",
    forUseIn: "BIZHUB 223, BIZHUB 224, BIZHUB 224 E, BIZHUB 282, BIZHUB 283, BIZHUB 284, BIZHUB 284 E, BIZHUB 362, BIZHUB 363, BIZHUB 364, BIZHUB 364 E, BIZHUB 423, BIZHUB 552, BIZHUB 554, BIZHUB 554 E, BIZHUB 652, BIZHUB 654, BIZHUB 654 E, BIZHUB 752, BIZHUB 754, BIZHUB 754 E"
  },
  {
    id: 15,
    name: "Black Toner Cartridge",
    price: 85.5,
    description: "MICR, Compatible with TN324K/TN514K",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49165",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49165",
    comments: "Priced Each, sold in Boxes of 1.  10 Boxes per Master Carton",
    forUseIn: "BIZHUB C 258, BIZHUB C 308, BIZHUB C 368"
  },
  {
    id: 16,
    name: "Yellow Toner Cartridge",
    price: 116.25,
    description: "Compatible with TN324Y/TN514Y",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49164",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49164",
    comments: "Priced Each, sold in Boxes of 1.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 258, BIZHUB C 308, BIZHUB C 368"
  },
  {
    id: 17,
    name: "Magenta Toner Cartridge",
    price: 116.25,
    description: "Compatible with TN324M/TN514M",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49163",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49163",
    comments: "Priced Each, sold in Boxes of 1.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 258, BIZHUB C 308, BIZHUB C 368"
  },
  {
    id: 18,
    name: "Cyan Toner Cartridge",
    price: 116.25,
    description: "Compatible with TN324C/TN514C",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49162",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49162",
    comments: "Priced Each, sold in Boxes of 1.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 258, BIZHUB C 308, BIZHUB C 368"
  },
  {
    id: 19,
    name: "Black Toner Cartridge",
    price: 85.5,
    description: "Compatible with TN324K/TN514K",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49161",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49161",
    comments: "Priced Each, sold in Boxes of 1.  6 Boxes per Master Carton",
    forUseIn: "BIZHUB C 258, BIZHUB C 308, BIZHUB C 368"
  },
  {
    id: 20,
    name: "Waste Toner Bottle",
    price: 14.95,
    description: "Packaged for use in Konica Minolta",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "43975",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "43975",
    comments: "Priced Each, sold in Boxes of 1.  10 Boxes per Master Carton",
    forUseIn: "BIZHUB C 220, BIZHUB C 221, BIZHUB C 221 S, BIZHUB C 224, BIZHUB C 224 E, BIZHUB C 280, BIZHUB C 281, BIZHUB C 284, BIZHUB C 284 E, BIZHUB C 360, BIZHUB C 364, BIZHUB C 364 E"
  },
  {
    id: 21,
    name: "Toner Cartridge Black",
    price: 64.95,
    description: "Compatible with TN328K",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49159",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49159",
    comments: "Priced Each, sold in Boxes of 1.  6 Boxes per Master Carton",
    forUseIn: "BIZHUB C 250 I, BIZHUB C 300 I"
  },
  {
    id: 22,
    name: "Toner Cartridge Yellow",
    price: 112.95,
    description: "Compatible with TN328Y",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49158",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49158",
    comments: "Priced Each, sold in Boxes of 1.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 250 I, BIZHUB C 300 I"
  },
  {
    id: 23,
    name: "Toner Cartridge Magenta",
    price: 112.95,
    description: "Compatible with TN328M",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49157",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49157",
    comments: "Priced Each, sold in Boxes of 1.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 250 I, BIZHUB C 300 I"
  },
  {
    id: 24,
    name: "Toner Cartridge Cyan",
    price: 112.95,
    description: "Compatible with TN328C",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49156",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49156",
    comments: "Priced Each, sold in Boxes of 1.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 250 I, BIZHUB C 300 I"
  },
  {
    id: 25,
    name: "Toner Cartridge Yellow",
    price: 109.95,
    description: "Compatible with TN321Y",
    category: "Konica Minolta",
    brand: "Katun Performance",
    image: "/product.png",
    rating: 4.5,
    reviews: 243,
    sku: "49154",
    oem: "Konica Minolta",
    oemPN: "N/P/N",
    katunPN: "49154",
    comments: "Priced Each, sold in Boxes of 1.  4 Boxes per Master Carton",
    forUseIn: "BIZHUB C 224, BIZHUB C 224 E, BIZHUB C 284, BIZHUB C 284 E, BIZHUB C 364, BIZHUB C 364 E, BIZHUB C 4"
 },
]